options(repos = c(CRAN = "https://cloud.r-project.org"))

install.packages("rmarkdown")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("tidyr")
install.packages("lubridate")
install.packages("sf")
install.packages("ggplot2")
install.packages("ggrepel")
install.packages("rosm")
install.packages("ggspatial")
install.packages("prettymapr")
install.packages("terra")
installed.packages("curl")
install.packages("raster")
install.packages("leaflet")
install.packages("htmltools")
install.packages("mapview")
install.packages("leafpop")